# Generated by Django 5.1.7 on 2025-06-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('matricule', models.CharField(max_length=15)),
                ('filiere', models.CharField(max_length=25)),
                ('mot_de_passe', models.CharField(max_length=100)),
            ],
        ),
    ]
