/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ui;

import Metier.GestionContact;
import entities.Etudiant;
import static java.lang.System.exit;
import java.time.DateTimeException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class JFrameEtudiant extends javax.swing.JFrame {

    /**
     * Creates new form Etudiant
     */
    public JFrameEtudiant() {
        initComponents();
        jButton1Ok.setVisible(false);
    }

    public JFrameEtudiant(Etudiant etudiant) {
        initComponents();
        jTextField1Code.setText(etudiant.getCode());
        jTextField2Nom.setText(etudiant.getNom());
        jTextField4Address.setText(etudiant.getAddress());
        jTextField5Email.setText(etudiant.getEmail());
        jTextField6TelNumber.setText(etudiant.getTelNumber());
        jComboBox1Cycle.setSelectedItem(etudiant.getCycle());
        jComboBox2Niveau.setSelectedItem(etudiant.getNiveau());
        jTextField1Jour.setText(etudiant.getDateNaiss().getDayOfMonth() + "");
        jTextField2Mois.setText(etudiant.getDateNaiss().getMonth() + "");
        jTextField3Annee.setText(etudiant.getDateNaiss().getYear() + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1Code = new javax.swing.JTextField();
        jTextField2Nom = new javax.swing.JTextField();
        jTextField4Address = new javax.swing.JTextField();
        jTextField5Email = new javax.swing.JTextField();
        jTextField6TelNumber = new javax.swing.JTextField();
        jComboBox1Cycle = new javax.swing.JComboBox<>();
        jComboBox2Niveau = new javax.swing.JComboBox<>();
        jButton1Annuler = new javax.swing.JButton();
        jButton2Enregistrer = new javax.swing.JButton();
        jTextField1Jour = new javax.swing.JTextField();
        jTextField2Mois = new javax.swing.JTextField();
        jTextField3Annee = new javax.swing.JTextField();
        jButton1Ok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GESTION DES ETUDIANTS");

        jLabel2.setText("Code");

        jLabel3.setText("Nom");

        jLabel4.setText("dateNaiss");

        jLabel5.setText("Address");

        jLabel6.setText("Email");

        jLabel7.setText("telNumber");

        jLabel8.setText("Cycle");

        jLabel9.setText("Niveau");

        jTextField1Code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1CodeActionPerformed(evt);
            }
        });

        jTextField4Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4AddressActionPerformed(evt);
            }
        });

        jTextField5Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5EmailActionPerformed(evt);
            }
        });

        jTextField6TelNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6TelNumberActionPerformed(evt);
            }
        });

        jComboBox1Cycle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Licence", "Ingenieur" }));
        jComboBox1Cycle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1CycleActionPerformed(evt);
            }
        });

        jComboBox2Niveau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        jButton1Annuler.setText("Annuler");
        jButton1Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1AnnulerActionPerformed(evt);
            }
        });

        jButton2Enregistrer.setText("Enregistrer");
        jButton2Enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2EnregistrerActionPerformed(evt);
            }
        });

        jTextField1Jour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1JourActionPerformed(evt);
            }
        });

        jButton1Ok.setText("OK");
        jButton1Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1OkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField6TelNumber))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1Cycle, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField5Email, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField4Address))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1Jour, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(jTextField2Mois, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField3Annee))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField2Nom))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1Code, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox2Niveau, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton1Annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(jButton2Enregistrer)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1Ok, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(365, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1Code, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2Nom, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField2Mois, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jTextField1Jour, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField3Annee))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4Address, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5Email, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6TelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1Cycle, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2Niveau, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2Enregistrer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1Annuler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1Ok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1CodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1CodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1CodeActionPerformed

    private void jTextField4AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4AddressActionPerformed

    private void jTextField6TelNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6TelNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6TelNumberActionPerformed

    private void jButton2EnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2EnregistrerActionPerformed
        // TODO add your handling code here:

        String code = jTextField1Code.getText();
        String nom = jTextField2Nom.getText();
        String addresse = jTextField4Address.getText();
        String telephone = jTextField6TelNumber.getText(); // Ensure this is the correct field
        String emaile = jTextField5Email.getText();
        String cycle = jComboBox1Cycle.getSelectedItem().toString();
        String Niveau = jComboBox2Niveau.getSelectedItem().toString();

        int annee, mois, joure;
        try {
            annee = Integer.parseInt(jTextField3Annee.getText());
            mois = Integer.parseInt(jTextField2Mois.getText());
            joure = Integer.parseInt(jTextField1Jour.getText());

            // Validate the date
            LocalDate dateNaissEnLocalDate = LocalDate.of(annee, mois, joure);

            // Validate email (simple regex for demonstration)
            if (!emaile.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")) {
                JOptionPane.showMessageDialog(this, "Adresse e-mail invalide !");
                return;
            }
            GestionContact gve = new GestionContact();
            gve.creerEtudiant(new Etudiant(code, nom, dateNaissEnLocalDate, addresse, emaile, telephone, cycle, Niveau));
            JOptionPane.showMessageDialog(this, "Étudiant enregistré avec succès !");
        } catch (DateTimeException e) {
            JOptionPane.showMessageDialog(this, "Date invalide !");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Veuillez entrer des valeurs numériques valides pour la date !");
        } catch (Exception ex) {
            Logger.getLogger(Etudiant.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Enregistrement de l'étudiant avec success !");
        } finally {
            // Reset fields or handle UI updates as necessary
            jTextField1Code.setText("");
            jTextField2Nom.setText("");
            jTextField6TelNumber.setText("");
            jTextField4Address.setText("");
            jTextField5Email.setText("");
            jTextField3Annee.setText("");
            jTextField2Mois.setText("");
            jTextField1Jour.setText("");

        }
    }//GEN-LAST:event_jButton2EnregistrerActionPerformed

    private void jTextField1JourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1JourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1JourActionPerformed

    private void jButton1AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1AnnulerActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1AnnulerActionPerformed

    private void jTextField5EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5EmailActionPerformed

    private void jComboBox1CycleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1CycleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1CycleActionPerformed

    private void jButton1OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1OkActionPerformed
        // TODO add your handling code here:
        String code = jTextField1Code.getText();
        String code1 = jTextField1Code.getText();
        String nom = jTextField2Nom.getText();
        String addresse = jTextField4Address.getText();
        String telephone = jTextField6TelNumber.getText();
        String emaile = jTextField5Email.getText();
        String cycle = jComboBox1Cycle.getSelectedItem().toString();
        String Niveau = jComboBox2Niveau.getSelectedItem().toString();
        int annee, joure, mois;
        try {
            annee = Integer.parseInt(jTextField3Annee.getText());
            mois = Integer.parseInt(jTextField2Mois.getText());
            joure = Integer.parseInt(jTextField1Jour.getText());
            LocalDate dateNaissEnLocalDate = LocalDate.of(annee, mois, joure);
            Etudiant etc = new Etudiant();
            etc.updateCode(code, nom, dateNaissEnLocalDate, addresse, emaile, telephone, cycle, Niveau, code1);
            GestionContact gve = new GestionContact();
            JOptionPane.showMessageDialog(this, "Étudiant modifier avec succès !");
        } catch (Exception ex) {
            Logger.getLogger(Etudiant.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Étudiant n'a pas ete modifier");
        }
    }//GEN-LAST:event_jButton1OkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameEtudiant().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Annuler;
    private javax.swing.JButton jButton1Ok;
    private javax.swing.JButton jButton2Enregistrer;
    private javax.swing.JComboBox<String> jComboBox1Cycle;
    private javax.swing.JComboBox<String> jComboBox2Niveau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1Code;
    private javax.swing.JTextField jTextField1Jour;
    private javax.swing.JTextField jTextField2Mois;
    private javax.swing.JTextField jTextField2Nom;
    private javax.swing.JTextField jTextField3Annee;
    private javax.swing.JTextField jTextField4Address;
    private javax.swing.JTextField jTextField5Email;
    private javax.swing.JTextField jTextField6TelNumber;
    // End of variables declaration//GEN-END:variables
}
