/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ui;

import Metier.GestionContact;
import entities.Agent;
import entities.Enseignant;
import entities.Etudiant;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class NewJFrameAccueile extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrameAccueil
     */
    public NewJFrameAccueile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1texte = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3ListerEnseignant = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem5AgentCreer = new javax.swing.JMenuItem();
        jMenuItem6ListerAgent = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Modifier");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Supprimer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField1texte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1texteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 865, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jTextField1texte, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1texte))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );

        jMenu3.setText("Etudiant");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Creer ");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("Lister Etudiant");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Enseignant");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jMenuItem3ListerEnseignant.setText("Creer");
        jMenuItem3ListerEnseignant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ListerEnseignantActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3ListerEnseignant);

        jMenuItem4.setText("Lister Enseignant");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Agent");

        jMenuItem5AgentCreer.setText("Creer");
        jMenuItem5AgentCreer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5AgentCreerActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem5AgentCreer);

        jMenuItem6ListerAgent.setText("Lister Agent");
        jMenuItem6ListerAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ListerAgentActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6ListerAgent);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling  code here:
        try {
            jTextField1texte.setText("Liste des étudiants");
            GestionContact gve = new GestionContact();
            List<Etudiant> listEtudiant = gve.listerEtudiant();
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("code");
            model.addColumn("Nom");
            model.addColumn("Date naissance");
            model.addColumn("Addresse");
            model.addColumn("Email");
            model.addColumn("Telephone");
            model.addColumn("cycle");
            model.addColumn("Niveau");
            for (Etudiant ad : listEtudiant) {
                model.addRow(new String[]{ad.getCode(), ad.getNom(), ad.getDateNaiss().toString(), ad.getAddress(), ad.getEmail(), ad.getTelNumber(), ad.getCycle(), ad.getNiveau()
                });
            }
            jTable1.setModel(model);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Erreur, veuillez contacter l'admin");
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ListerEnseignantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ListerEnseignantActionPerformed
        // TODO add your handling code here:
        JFrameEnseignant men = new JFrameEnseignant();
        men.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ListerEnseignantActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JFrameEtudiant e = new JFrameEtudiant();
        e.setVisible(true);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        try {
            jTextField1texte.setText("Liste des Enseignants");
            GestionContact gve = new GestionContact();

            List<Enseignant> listEtudiant = gve.listerEnseignant();
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("code");
            model.addColumn("Nom");
            model.addColumn("Date naissance");
            model.addColumn("Addresse");
            model.addColumn("Email");
            model.addColumn("Telephone");
            model.addColumn("Statut");

            for (Enseignant ad : listEtudiant) {
                model.addRow(new String[]{ad.getCode(), ad.getNom(), ad.getDateNaiss().toString(), ad.getAddress(), ad.getEmail(), ad.getTelNumber(), ad.getStatut()
                });
            }
            jTable1.setModel(model);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Erreur, veuillez contacter l'admin");
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5AgentCreerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5AgentCreerActionPerformed
        // TODO add your handling code here:
        JFrameAgent erica = new JFrameAgent();
        erica.setVisible(true);
    }//GEN-LAST:event_jMenuItem5AgentCreerActionPerformed

    private void jMenuItem6ListerAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ListerAgentActionPerformed
        // TODO add your handling code here:
        try {

            jTextField1texte.setText("Liste des Agent");
            GestionContact gve = new GestionContact();
            List<Agent> listAgent = gve.listerAgent();
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("code");
            model.addColumn("Nom");
            model.addColumn("Date naissance");
            model.addColumn("Addresse");
            model.addColumn("Email");
            model.addColumn("Telephone");
            model.addColumn("salaire");
            model.addColumn("statut");
            model.addColumn("categorie");
            model.addColumn("indice salaire");
            model.addColumn("Occupation");

            for (Agent ad : listAgent) {
                model.addRow(new String[]{ad.getCode(), ad.getNom(), ad.getDateNaiss().toString(), ad.getAddress(), ad.getEmail(), ad.getTelNumber(), ad.getSalaire(), ad.getStatut(), ad.getCategorie(), ad.getIndicesalaire(), ad.getOccupation()
                });
            }
            jTable1.setModel(model);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Erreur, veuillez contacter l'admin");
        }

    }//GEN-LAST:event_jMenuItem6ListerAgentActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        try {
            String textFieldText = jTextField1texte.getText();

            if (textFieldText.equals("Liste des étudiants")) {
                Etudiant e = new Etudiant();
                String coder = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
                JFrameEtudiant ste = new JFrameEtudiant(e.GetOne(coder));
                ste.setVisible(true);

            } else if (textFieldText.equals("Liste des Enseignants")) {
                Enseignant e = new Enseignant();
                String coder = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
                JFrameEnseignant ste = new JFrameEnseignant(e.getOne(coder));
                ste.setVisible(true);
            } else {
                Agent e = new Agent();
                String coder = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
                JFrameAgent ste = new JFrameAgent(e.getOneAgent(coder));
                ste.setVisible(true);
            }
        } catch (SQLException e) {
            e.printStackTrace(); // Ajoutez une gestion des erreurs
        }
//JButton okButton =(JButton)JFrameEtudiant.getCompoment(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            String textFieldText = jTextField1texte.getText(); // Récupérer le texte une seule fois

            if (textFieldText.equals("Liste des étudiants")) {
                if (jTable1.getSelectedRow() != -1) {
                    String coder = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
                    Etudiant e = new Etudiant();
                    e.deleteEtudiantById(coder);
                }
            } else if (textFieldText.equals("Liste des Enseignants")) {
                if (jTable1.getSelectedRow() != -1) {
                    String coder = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
                    Enseignant e = new Enseignant();
                    e.deleteEtudiantById(coder);
                }
            } else {
                if (jTable1.getSelectedRow() != -1) {
                    String coder = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
                    Agent e = new Agent();
                    e.deleteAgentById(coder);
                }
            }
        } catch (SQLException e) {
            e.printStackTrace(); // Ajoutez une gestion des erreurs
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1texteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1texteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1texteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrameAccueile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrameAccueile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrameAccueile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrameAccueile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrameAccueile().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3ListerEnseignant;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5AgentCreer;
    private javax.swing.JMenuItem jMenuItem6ListerAgent;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1texte;
    // End of variables declaration//GEN-END:variables
}
