# Generated by Django 5.1.7 on 2025-04-14 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrateur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('superficie', models.FloatField()),
                ('description', models.CharField(max_length=300)),
                ('Administrateur', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrateur.administrateur')),
            ],
        ),
    ]
