# Generated by Django 5.1.7 on 2025-04-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_quartier', models.CharField(max_length=50)),
                ('ville', models.CharField(max_length=50)),
                ('superficies', models.FloatField()),
            ],
        ),
    ]
