# Generated by Django 5.1.7 on 2025-06-27 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etudiant', '0001_initial'),
        ('logement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('commentaire', models.TextField()),
                ('note', models.IntegerField()),
                ('datePublication', models.DateTimeField(auto_now_add=True)),
                ('etudiant_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etudiant.etudiant')),
                ('logement_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logement.logement')),
            ],
        ),
    ]
