# Generated by Django 5.1.7 on 2025-04-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('user', 'Utilisateur simple')], default='user', max_length=10)),
            ],
        ),
    ]
