# Generated by Django 5.1.7 on 2025-04-08 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quartier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maison',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coleur', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=30)),
                ('superficie', models.FloatField()),
                ('type_maison', models.CharField(max_length=40)),
                ('nombre_douche', models.IntegerField()),
                ('quartier', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quartier.quartier')),
            ],
        ),
    ]
