# Generated by Django 5.1.7 on 2025-04-14 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorie', '__first__'),
        ('quartier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maison',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('adresse', models.CharField(max_length=200)),
                ('superficie', models.FloatField()),
                ('quartier', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quartier.quartier')),
                ('type_maison', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='categorie.categorie')),
            ],
        ),
    ]
