# Generated by Django 5.1.7 on 2025-06-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mot_de_passe', models.CharField(max_length=100)),
                ('entreprise', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=15)),
            ],
        ),
    ]
