# Generated by Django 5.1.7 on 2025-04-24 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrateur', '0001_initial'),
        ('evenement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evenement.evenement')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrateur.utilisateur')),
            ],
            options={
                'unique_together': {('utilisateur', 'evenement')},
            },
        ),
    ]
